'use client'
import StyledComponentsRegistry from '@/lib/antd.registry'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HeaderModule from './components/header.module'
import NavbarModule from './components/navbar.module'

import { Breadcrumb, Layout, Menu, theme } from 'antd';
import { Content } from 'antd/es/layout/layout'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();

  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: 0 }}>
        <StyledComponentsRegistry>
          <Layout>
            <HeaderModule />
            <Layout>
              <NavbarModule />
              <Layout style={{ padding: '0 24px 24px' }}>
                <Breadcrumb style={{ margin: '16px 0' }}>

                </Breadcrumb>
                <Content
                  style={{
                    padding: 24,
                    margin: 0,
                    minHeight: 280,
                    background: colorBgContainer,
                    borderRadius: borderRadiusLG,
                  }}
                >
                  {children}
                </Content>
              </Layout>

            </Layout>
          </Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
